import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";
import { lstat, readFile, readdir, realpath } from "node:fs/promises";
import { dirname, relative, resolve, sep } from "node:path";

import { IntegrationPlanError } from "./plan-error.js";

export const PROVIDER_NAME = "tauri-plugin-wdio-webdriver";
export const PROVIDER_KIND = "provider" as const;
export const PROVIDER_SOURCE_ROOT = `provider/${PROVIDER_NAME}`;
export const PROVIDER_STAGED_ROOT = `.pumarejo/provider/${PROVIDER_NAME}`;
export const PROVIDER_CARGO_PATH = `../${PROVIDER_STAGED_ROOT}`;
export const PROVIDER_ATTRIBUTION_PREFIX = `provider:${PROVIDER_NAME}:`;
export const MAX_PROVIDER_FILE_BYTES = 4 * 1024 * 1024;

function hash(content: string): string {
  return createHash("sha256").update(content, "utf8").digest("hex");
}

export const PROVIDER_SOURCE_ALLOWLIST = [
  "build.rs",
  "Cargo.toml",
  "LICENSE",
  "PATCHES.md",
  "permissions/autogenerated/commands/request_dialog.toml",
  "permissions/autogenerated/reference.md",
  "permissions/default.toml",
  "permissions/schemas/schema.json",
  "README.md",
  "src/desktop.rs",
  "src/dialog.rs",
  "src/error.rs",
  "src/lib.rs",
  "src/mobile.rs",
  "src/platform/alert_state.rs",
  "src/platform/android.rs",
  "src/platform/executor.rs",
  "src/platform/ios.rs",
  "src/platform/linux.rs",
  "src/platform/macos.rs",
  "src/platform/mod.rs",
  "src/platform/windows.rs",
  "src/server/handlers/actions.rs",
  "src/server/handlers/alert.rs",
  "src/server/handlers/cookie.rs",
  "src/server/handlers/direct_eval.rs",
  "src/server/handlers/document.rs",
  "src/server/handlers/element.rs",
  "src/server/handlers/frame.rs",
  "src/server/handlers/mod.rs",
  "src/server/handlers/navigation.rs",
  "src/server/handlers/print.rs",
  "src/server/handlers/screenshot.rs",
  "src/server/handlers/script.rs",
  "src/server/handlers/session.rs",
  "src/server/handlers/shadow.rs",
  "src/server/handlers/tauri_dialog.rs",
  "src/server/handlers/timeouts.rs",
  "src/server/handlers/window.rs",
  "src/server/mod.rs",
  "src/server/response.rs",
  "src/server/router.rs",
  "src/webdriver/element.rs",
  "src/webdriver/locator.rs",
  "src/webdriver/mod.rs",
  "src/webdriver/session.rs",
].sort();

export interface ProviderBundleEntry {
  readonly sourceRelativePath: string;
  readonly content: string;
  readonly afterHash: string;
}

function inside(root: string, candidate: string): boolean {
  const resolvedRoot = resolve(root);
  const resolvedCandidate = resolve(candidate);
  const difference = relative(root, candidate);
  return (
    difference !== "" &&
    difference !== ".." &&
    !difference.startsWith(`..${sep}`) &&
    resolvedCandidate.startsWith(`${resolvedRoot}${sep}`)
  );
}

function safePath(root: string, sourceRelativePath: string): string {
  const candidate = resolve(root, sourceRelativePath);
  if (!inside(root, candidate)) {
    throw new IntegrationPlanError("UNSAFE_TARGET");
  }
  return candidate;
}

function packageProviderRoot(): string {
  // Both src/installer and dist/installer are two levels below the package
  // root, so this remains valid in tests and in an installed tarball.
  const packageRoot = resolve(
    dirname(fileURLToPath(import.meta.url)),
    "..",
    "..",
  );
  return resolve(packageRoot, "dist", PROVIDER_SOURCE_ROOT);
}

function developmentProviderRoot(): string {
  return resolve(
    dirname(fileURLToPath(import.meta.url)),
    "..",
    "..",
    "vendor",
    PROVIDER_NAME,
  );
}

async function regularFile(path: string): Promise<void> {
  const metadata = await lstat(path);
  if (
    metadata.isSymbolicLink() ||
    !metadata.isFile() ||
    metadata.size > MAX_PROVIDER_FILE_BYTES ||
    (await realpath(path)) !== path
  ) {
    throw new IntegrationPlanError("UNSAFE_TARGET");
  }
}

export async function resolveProviderSourceRoot(): Promise<string> {
  const packaged = packageProviderRoot();
  try {
    const metadata = await lstat(packaged);
    if (metadata.isSymbolicLink() || !metadata.isDirectory()) {
      throw new IntegrationPlanError("UNSAFE_TARGET");
    }
    if ((await realpath(packaged)) !== packaged) {
      throw new IntegrationPlanError("UNSAFE_TARGET");
    }
    return packaged;
  } catch (error) {
    if (error instanceof IntegrationPlanError) throw error;
    const development = developmentProviderRoot();
    try {
      const metadata = await lstat(development);
      if (metadata.isSymbolicLink() || !metadata.isDirectory()) {
        throw new IntegrationPlanError("UNSAFE_TARGET");
      }
      if ((await realpath(development)) !== development) {
        throw new IntegrationPlanError("UNSAFE_TARGET");
      }
      return development;
    } catch (fallbackError) {
      if (fallbackError instanceof IntegrationPlanError) throw fallbackError;
      throw new IntegrationPlanError("WRITE_FAILED", { cause: fallbackError });
    }
  }
}

export async function readProviderBundle(): Promise<
  readonly ProviderBundleEntry[]
> {
  const root = await resolveProviderSourceRoot();
  const entries: ProviderBundleEntry[] = [];
  for (const sourceRelativePath of PROVIDER_SOURCE_ALLOWLIST) {
    const path = safePath(root, sourceRelativePath);
    try {
      await regularFile(path);
      const content = await readFile(path, "utf8");
      entries.push({
        sourceRelativePath,
        content,
        afterHash: hash(content),
      });
    } catch (error) {
      if (error instanceof IntegrationPlanError) throw error;
      throw new IntegrationPlanError("WRITE_FAILED", { cause: error });
    }
  }
  return entries;
}

export function providerAttribution(sourceRelativePath: string): string {
  return `${PROVIDER_ATTRIBUTION_PREFIX}${sourceRelativePath}`;
}

export function providerSourcePathFromAttribution(
  attribution: readonly string[],
): string | undefined {
  if (attribution.length !== 1) return undefined;
  const value = attribution[0] ?? "";
  if (!value.startsWith(PROVIDER_ATTRIBUTION_PREFIX)) return undefined;
  const sourceRelativePath = value.slice(PROVIDER_ATTRIBUTION_PREFIX.length);
  return PROVIDER_SOURCE_ALLOWLIST.includes(sourceRelativePath)
    ? sourceRelativePath
    : undefined;
}

async function listStagedFiles(root: string): Promise<{
  readonly files: readonly string[];
  readonly directories: readonly string[];
}> {
  const files: string[] = [];
  const directories: string[] = [];
  const visit = async (directory: string, prefix: string): Promise<void> => {
    const entries = await readdir(directory, { withFileTypes: true });
    for (const entry of entries) {
      const sourceRelativePath = prefix
        ? `${prefix}/${entry.name}`
        : entry.name;
      const path = safePath(root, sourceRelativePath);
      if (entry.isSymbolicLink())
        throw new IntegrationPlanError("UNSAFE_TARGET");
      if (entry.isDirectory()) {
        directories.push(sourceRelativePath.replaceAll("\\", "/"));
        await visit(path, sourceRelativePath);
      } else if (entry.isFile()) {
        await regularFile(path);
        files.push(sourceRelativePath.replaceAll("\\", "/"));
      } else {
        throw new IntegrationPlanError("UNSAFE_TARGET");
      }
    }
  };
  await visit(root, "");
  return { files: files.sort(), directories: directories.sort() };
}

export async function validateProviderStaging(
  projectRoot: string,
  expectedEntries: readonly { readonly relativePath: string }[],
): Promise<void> {
  const stageRoot = safePath(resolve(projectRoot), PROVIDER_STAGED_ROOT);
  try {
    const metadata = await lstat(stageRoot);
    if (metadata.isSymbolicLink() || !metadata.isDirectory()) {
      throw new IntegrationPlanError("UNSAFE_TARGET");
    }
    if ((await realpath(stageRoot)) !== stageRoot) {
      throw new IntegrationPlanError("UNSAFE_TARGET");
    }
  } catch (error) {
    if (error instanceof IntegrationPlanError) throw error;
    throw new IntegrationPlanError("ALREADY_INTEGRATED_MODIFIED", {
      cause: error,
    });
  }
  const listed = await listStagedFiles(stageRoot);
  const actual = listed.files;
  const expected = expectedEntries
    .map((entry) => {
      if (!entry.relativePath.startsWith(`${PROVIDER_STAGED_ROOT}/`)) {
        throw new IntegrationPlanError("ALREADY_INTEGRATED_MODIFIED");
      }
      return entry.relativePath.slice(`${PROVIDER_STAGED_ROOT}/`.length);
    })
    .sort();
  if (
    actual.length !== expected.length ||
    actual.some((path, index) => path !== expected[index])
  ) {
    throw new IntegrationPlanError("ALREADY_INTEGRATED_MODIFIED");
  }
  const expectedDirectories = new Set<string>();
  for (const sourceRelativePath of expected) {
    const segments = sourceRelativePath.split("/");
    segments.pop();
    for (let index = 1; index <= segments.length; index += 1) {
      expectedDirectories.add(segments.slice(0, index).join("/"));
    }
  }
  if (
    listed.directories.length !== expectedDirectories.size ||
    listed.directories.some((directory) => !expectedDirectories.has(directory))
  ) {
    throw new IntegrationPlanError("ALREADY_INTEGRATED_MODIFIED");
  }
  const bundle = await readProviderBundle();
  const expectedHashes = new Map(
    bundle.map((entry) => [entry.sourceRelativePath, entry.afterHash]),
  );
  for (const sourceRelativePath of actual) {
    const stagedPath = safePath(stageRoot, sourceRelativePath);
    const source = await readFile(stagedPath, "utf8");
    if (expectedHashes.get(sourceRelativePath) !== hash(source)) {
      throw new IntegrationPlanError("ALREADY_INTEGRATED_MODIFIED");
    }
  }
}
